#############################################################################
# Makefile for building: ../bin/RadarDisplay
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  RadarDisplay.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile RadarDisplay.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICKWIDGETS_LIB -DQT_CHARTS_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I../obj/MOC -I../obj/UI -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RadarDisplay1.0.0
DISTDIR = /home/shridhar/obj/OBJ/RadarDisplay1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -lqgis_core -lqgis_gui -lqgis_analysis -lgeos_c -lproj -lspatialindex /usr/lib/x86_64-linux-gnu/libQt5QuickWidgets.so /usr/lib/x86_64-linux-gnu/libQt5Charts.so /usr/lib/x86_64-linux-gnu/libQt5MultimediaWidgets.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5QuickControls2.so /usr/lib/x86_64-linux-gnu/libQt5Quick.so /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5QmlModels.so /usr/lib/x86_64-linux-gnu/libQt5Qml.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ../obj/OBJ/

####### Files

SOURCES       = CoordinateConverter.cpp \
		MapDisplay/canalyticswidget.cpp \
		MapDisplay/cchartswidget.cpp \
		MapDisplay/cconfigpanelwidget.cpp \
		MapDisplay/chealthmonitorwidget.cpp \
		MapDisplay/chomepositionhighlightlayer.cpp \
		MapDisplay/cinterfacespanelwidget.cpp \
		MapDisplay/cpredictivemaintenancewidget.cpp \
		MapDisplay/cppilayer.cpp \
		MapDisplay/crecordingwidget.cpp \
		MapDisplay/creplaywindow.cpp \
		MapDisplay/csearchbeamlayer.cpp \
		MapDisplay/csimulationwidget.cpp \
		MapDisplay/ctracklayer.cpp \
		MapDisplay/ctracktablewidget.cpp \
		MapDisplay/customgradiantfillsymbollayer.cpp \
		cdatawarehouse.cpp \
		cdrone.cpp \
		cudpreceiver.cpp \
		main.cpp \
		cmapmainwindow.cpp \
		cppiwindow.cpp \
		ccontrolswindow.cpp \
		MapDisplay/cmapcanvas.cpp \
		matrix.cpp ../obj/RCC/qrc_myRes.cpp \
		../obj/MOC/moc_canalyticswidget.cpp \
		../obj/MOC/moc_cchartswidget.cpp \
		../obj/MOC/moc_cconfigpanelwidget.cpp \
		../obj/MOC/moc_chealthmonitorwidget.cpp \
		../obj/MOC/moc_chomepositionhighlightlayer.cpp \
		../obj/MOC/moc_cinterfacespanelwidget.cpp \
		../obj/MOC/moc_cpredictivemaintenancewidget.cpp \
		../obj/MOC/moc_cppilayer.cpp \
		../obj/MOC/moc_crecordingwidget.cpp \
		../obj/MOC/moc_creplaywindow.cpp \
		../obj/MOC/moc_csimulationwidget.cpp \
		../obj/MOC/moc_ctracklayer.cpp \
		../obj/MOC/moc_ctracktablewidget.cpp \
		../obj/MOC/moc_cdatawarehouse.cpp \
		../obj/MOC/moc_cdrone.cpp \
		../obj/MOC/moc_cmapmainwindow.cpp \
		../obj/MOC/moc_cppiwindow.cpp \
		../obj/MOC/moc_ccontrolswindow.cpp \
		../obj/MOC/moc_cmapcanvas.cpp \
		../obj/MOC/moc_cudpreceiver.cpp
OBJECTS       = ../obj/OBJ/CoordinateConverter.o \
		../obj/OBJ/canalyticswidget.o \
		../obj/OBJ/cchartswidget.o \
		../obj/OBJ/cconfigpanelwidget.o \
		../obj/OBJ/chealthmonitorwidget.o \
		../obj/OBJ/chomepositionhighlightlayer.o \
		../obj/OBJ/cinterfacespanelwidget.o \
		../obj/OBJ/cpredictivemaintenancewidget.o \
		../obj/OBJ/cppilayer.o \
		../obj/OBJ/crecordingwidget.o \
		../obj/OBJ/creplaywindow.o \
		../obj/OBJ/csearchbeamlayer.o \
		../obj/OBJ/csimulationwidget.o \
		../obj/OBJ/ctracklayer.o \
		../obj/OBJ/ctracktablewidget.o \
		../obj/OBJ/customgradiantfillsymbollayer.o \
		../obj/OBJ/cdatawarehouse.o \
		../obj/OBJ/cdrone.o \
		../obj/OBJ/cudpreceiver.o \
		../obj/OBJ/main.o \
		../obj/OBJ/cmapmainwindow.o \
		../obj/OBJ/cppiwindow.o \
		../obj/OBJ/ccontrolswindow.o \
		../obj/OBJ/cmapcanvas.o \
		../obj/OBJ/matrix.o \
		../obj/OBJ/qrc_myRes.o \
		../obj/OBJ/moc_canalyticswidget.o \
		../obj/OBJ/moc_cchartswidget.o \
		../obj/OBJ/moc_cconfigpanelwidget.o \
		../obj/OBJ/moc_chealthmonitorwidget.o \
		../obj/OBJ/moc_chomepositionhighlightlayer.o \
		../obj/OBJ/moc_cinterfacespanelwidget.o \
		../obj/OBJ/moc_cpredictivemaintenancewidget.o \
		../obj/OBJ/moc_cppilayer.o \
		../obj/OBJ/moc_crecordingwidget.o \
		../obj/OBJ/moc_creplaywindow.o \
		../obj/OBJ/moc_csimulationwidget.o \
		../obj/OBJ/moc_ctracklayer.o \
		../obj/OBJ/moc_ctracktablewidget.o \
		../obj/OBJ/moc_cdatawarehouse.o \
		../obj/OBJ/moc_cdrone.o \
		../obj/OBJ/moc_cmapmainwindow.o \
		../obj/OBJ/moc_cppiwindow.o \
		../obj/OBJ/moc_ccontrolswindow.o \
		../obj/OBJ/moc_cmapcanvas.o \
		../obj/OBJ/moc_cudpreceiver.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RadarDisplay.pro CoordinateConverter.h \
		MapDisplay/canalyticswidget.h \
		MapDisplay/cchartswidget.h \
		MapDisplay/cconfigpanelwidget.h \
		MapDisplay/chealthmonitorwidget.h \
		MapDisplay/cinterfacespanelwidget.h \
		MapDisplay/cpredictivemaintenancewidget.h \
		MapDisplay/cppilayer.h \
		MapDisplay/crecordingwidget.h \
		MapDisplay/creplaywindow.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/csimulationwidget.h \
		MapDisplay/ctracklayer.h \
		MapDisplay/ctracktablewidget.h \
		MapDisplay/customgradiantfillsymbollayer.h \
		cdatawarehouse.h \
		cdrone.h \
		cmapmainwindow.h \
		cppiwindow.h \
		ccontrolswindow.h \
		MapDisplay/cmapcanvas.h \
		cudpreceiver.h \
		globalmacros.h \
		globalstructs.h \
		matrix.h CoordinateConverter.cpp \
		MapDisplay/canalyticswidget.cpp \
		MapDisplay/cchartswidget.cpp \
		MapDisplay/cconfigpanelwidget.cpp \
		MapDisplay/chealthmonitorwidget.cpp \
		MapDisplay/cinterfacespanelwidget.cpp \
		MapDisplay/cpredictivemaintenancewidget.cpp \
		MapDisplay/cppilayer.cpp \
		MapDisplay/crecordingwidget.cpp \
		MapDisplay/creplaywindow.cpp \
		MapDisplay/csearchbeamlayer.cpp \
		MapDisplay/csimulationwidget.cpp \
		MapDisplay/ctracklayer.cpp \
		MapDisplay/ctracktablewidget.cpp \
		MapDisplay/customgradiantfillsymbollayer.cpp \
		cdatawarehouse.cpp \
		cdrone.cpp \
		cudpreceiver.cpp \
		main.cpp \
		cmapmainwindow.cpp \
		cppiwindow.cpp \
		ccontrolswindow.cpp \
		MapDisplay/cmapcanvas.cpp \
		matrix.cpp
QMAKE_TARGET  = RadarDisplay
DESTDIR       = ../bin/
TARGET        = ../bin/RadarDisplay


first: all
####### Build rules

../bin/RadarDisplay: ../obj/UI/ui_cmapmainwindow.h $(OBJECTS)  
	@test -d ../bin/ || mkdir -p ../bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

# Disabled Makefile regeneration (qmake not available)
Makefile_disabled: RadarDisplay.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		RadarDisplay.pro \
		myRes.qrc
	@echo "Skipping Makefile regeneration (qmake not available)"
	@touch Makefile
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
RadarDisplay.pro:
myRes.qrc:
qmake: FORCE
	@echo "Skipping qmake (not available)"

qmake_all: FORCE


all: Makefile ../bin/RadarDisplay

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents myRes.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents CoordinateConverter.h MapDisplay/canalyticswidget.h MapDisplay/cchartswidget.h MapDisplay/cconfigpanelwidget.h MapDisplay/chealthmonitorwidget.h MapDisplay/cinterfacespanelwidget.h MapDisplay/cpredictivemaintenancewidget.h MapDisplay/cppilayer.h MapDisplay/crecordingwidget.h MapDisplay/creplaywindow.h MapDisplay/csearchbeamlayer.h MapDisplay/csimulationwidget.h MapDisplay/ctracklayer.h MapDisplay/ctracktablewidget.h MapDisplay/customgradiantfillsymbollayer.h cdatawarehouse.h cdrone.h cmapmainwindow.h cppiwindow.h ccontrolswindow.h MapDisplay/cmapcanvas.h cudpreceiver.h globalmacros.h globalstructs.h matrix.h $(DISTDIR)/
	$(COPY_FILE) --parents CoordinateConverter.cpp MapDisplay/canalyticswidget.cpp MapDisplay/cchartswidget.cpp MapDisplay/cconfigpanelwidget.cpp MapDisplay/chealthmonitorwidget.cpp MapDisplay/cinterfacespanelwidget.cpp MapDisplay/cpredictivemaintenancewidget.cpp MapDisplay/cppilayer.cpp MapDisplay/crecordingwidget.cpp MapDisplay/creplaywindow.cpp MapDisplay/csearchbeamlayer.cpp MapDisplay/csimulationwidget.cpp MapDisplay/ctracklayer.cpp MapDisplay/ctracktablewidget.cpp MapDisplay/customgradiantfillsymbollayer.cpp cdatawarehouse.cpp cdrone.cpp cudpreceiver.cpp main.cpp cmapmainwindow.cpp cppiwindow.cpp ccontrolswindow.cpp MapDisplay/cmapcanvas.cpp matrix.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cmapmainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: ../obj/RCC/qrc_myRes.cpp
compiler_rcc_clean:
	-$(DEL_FILE) ../obj/RCC/qrc_myRes.cpp
../obj/RCC/qrc_myRes.cpp: myRes.qrc \
		/usr/lib/qt5/bin/rcc \
		MainView.qml \
		Icons/SettingsIcon.qml \
		Icons/ZoomFitIcon.qml \
		Icons/LoadMapIcon.qml \
		Icons/IconButton.qml \
		Icons/DisableMapIcon.qml \
		Icons/TableIcon.qml \
		Icons/CompassIcon.qml \
		Icons/HomeIcon.qml \
		Icons/GridIcon.qml \
		resources/drone_icon.png \
		resources/drone_icon.svg
	/usr/lib/qt5/bin/rcc -name myRes myRes.qrc -o ../obj/RCC/qrc_myRes.cpp

compiler_moc_predefs_make_all: ../obj/MOC/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) ../obj/MOC/moc_predefs.h
../obj/MOC/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o ../obj/MOC/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: ../obj/MOC/moc_canalyticswidget.cpp ../obj/MOC/moc_cchartswidget.cpp ../obj/MOC/moc_cconfigpanelwidget.cpp ../obj/MOC/moc_chealthmonitorwidget.cpp ../obj/MOC/moc_cinterfacespanelwidget.cpp ../obj/MOC/moc_cpredictivemaintenancewidget.cpp ../obj/MOC/moc_cppilayer.cpp ../obj/MOC/moc_crecordingwidget.cpp ../obj/MOC/moc_creplaywindow.cpp ../obj/MOC/moc_csimulationwidget.cpp ../obj/MOC/moc_ctracklayer.cpp ../obj/MOC/moc_ctracktablewidget.cpp ../obj/MOC/moc_cdatawarehouse.cpp ../obj/MOC/moc_cdrone.cpp ../obj/MOC/moc_cmapmainwindow.cpp ../obj/MOC/moc_cppiwindow.cpp ../obj/MOC/moc_ccontrolswindow.cpp ../obj/MOC/moc_cmapcanvas.cpp ../obj/MOC/moc_cudpreceiver.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) ../obj/MOC/moc_canalyticswidget.cpp ../obj/MOC/moc_cchartswidget.cpp ../obj/MOC/moc_cconfigpanelwidget.cpp ../obj/MOC/moc_chealthmonitorwidget.cpp ../obj/MOC/moc_cinterfacespanelwidget.cpp ../obj/MOC/moc_cpredictivemaintenancewidget.cpp ../obj/MOC/moc_cppilayer.cpp ../obj/MOC/moc_crecordingwidget.cpp ../obj/MOC/moc_creplaywindow.cpp ../obj/MOC/moc_csimulationwidget.cpp ../obj/MOC/moc_ctracklayer.cpp ../obj/MOC/moc_ctracktablewidget.cpp ../obj/MOC/moc_cdatawarehouse.cpp ../obj/MOC/moc_cdrone.cpp ../obj/MOC/moc_cmapmainwindow.cpp ../obj/MOC/moc_cppiwindow.cpp ../obj/MOC/moc_ccontrolswindow.cpp ../obj/MOC/moc_cmapcanvas.cpp ../obj/MOC/moc_cudpreceiver.cpp
../obj/MOC/moc_canalyticswidget.cpp: MapDisplay/canalyticswidget.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/canalyticswidget.h -o ../obj/MOC/moc_canalyticswidget.cpp

../obj/MOC/moc_cchartswidget.cpp: MapDisplay/cchartswidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cchartswidget.h -o ../obj/MOC/moc_cchartswidget.cpp

../obj/MOC/moc_cconfigpanelwidget.cpp: MapDisplay/cconfigpanelwidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cconfigpanelwidget.h -o ../obj/MOC/moc_cconfigpanelwidget.cpp

../obj/MOC/moc_chealthmonitorwidget.cpp: MapDisplay/chealthmonitorwidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/chealthmonitorwidget.h -o ../obj/MOC/moc_chealthmonitorwidget.cpp

../obj/MOC/moc_chomepositionhighlightlayer.cpp: MapDisplay/chomepositionhighlightlayer.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/chomepositionhighlightlayer.h -o ../obj/MOC/moc_chomepositionhighlightlayer.cpp

../obj/MOC/moc_cinterfacespanelwidget.cpp: MapDisplay/cinterfacespanelwidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cinterfacespanelwidget.h -o ../obj/MOC/moc_cinterfacespanelwidget.cpp

../obj/MOC/moc_cpredictivemaintenancewidget.cpp: MapDisplay/cpredictivemaintenancewidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cpredictivemaintenancewidget.h -o ../obj/MOC/moc_cpredictivemaintenancewidget.cpp

../obj/MOC/moc_cppilayer.cpp: MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cppilayer.h -o ../obj/MOC/moc_cppilayer.cpp

../obj/MOC/moc_crecordingwidget.cpp: MapDisplay/crecordingwidget.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/crecordingwidget.h -o ../obj/MOC/moc_crecordingwidget.cpp

../obj/MOC/moc_creplaywindow.cpp: MapDisplay/creplaywindow.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/creplaywindow.h -o ../obj/MOC/moc_creplaywindow.cpp

../obj/MOC/moc_csimulationwidget.cpp: MapDisplay/csimulationwidget.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/csimulationwidget.h -o ../obj/MOC/moc_csimulationwidget.cpp

../obj/MOC/moc_ctracklayer.cpp: MapDisplay/ctracklayer.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/ctracklayer.h -o ../obj/MOC/moc_ctracklayer.cpp

../obj/MOC/moc_ctracktablewidget.cpp: MapDisplay/ctracktablewidget.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/ctracktablewidget.h -o ../obj/MOC/moc_ctracktablewidget.cpp

../obj/MOC/moc_cdatawarehouse.cpp: cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cdatawarehouse.h -o ../obj/MOC/moc_cdatawarehouse.cpp

../obj/MOC/moc_cdrone.cpp: cdrone.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cdrone.h -o ../obj/MOC/moc_cdrone.cpp

../obj/MOC/moc_cmapmainwindow.cpp: cmapmainwindow.h \
		MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cmapmainwindow.h -o ../obj/MOC/moc_cmapmainwindow.cpp

../obj/MOC/moc_cppiwindow.cpp: cppiwindow.h \
		MapDisplay/canalyticswidget.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cppiwindow.h -o ../obj/MOC/moc_cppiwindow.cpp

../obj/MOC/moc_ccontrolswindow.cpp: ccontrolswindow.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include ccontrolswindow.h -o ../obj/MOC/moc_ccontrolswindow.cpp

../obj/MOC/moc_cmapcanvas.cpp: MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MapDisplay/cmapcanvas.h -o ../obj/MOC/moc_cmapcanvas.cpp

../obj/MOC/moc_cudpreceiver.cpp: cudpreceiver.h \
		globalstructs.h \
		../obj/MOC/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/shridhar/obj/MOC/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/shridhar/ZIRDS -I/usr/include/qgis -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtQuickWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtMultimediaWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtQuickControls2 -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtQmlModels -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtConcurrent -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include cudpreceiver.h -o ../obj/MOC/moc_cudpreceiver.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ../obj/UI/ui_cmapmainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ../obj/UI/ui_cmapmainwindow.h
../obj/UI/ui_cmapmainwindow.h: cmapmainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic cmapmainwindow.ui -o ../obj/UI/ui_cmapmainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

../obj/OBJ/CoordinateConverter.o: CoordinateConverter.cpp CoordinateConverter.h \
		matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/CoordinateConverter.o CoordinateConverter.cpp

../obj/OBJ/canalyticswidget.o: MapDisplay/canalyticswidget.cpp MapDisplay/canalyticswidget.h \
		globalstructs.h \
		cdatawarehouse.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/canalyticswidget.o MapDisplay/canalyticswidget.cpp

../obj/OBJ/cchartswidget.o: MapDisplay/cchartswidget.cpp MapDisplay/cchartswidget.h \
		cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cchartswidget.o MapDisplay/cchartswidget.cpp

../obj/OBJ/cconfigpanelwidget.o: MapDisplay/cconfigpanelwidget.cpp MapDisplay/cconfigpanelwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cconfigpanelwidget.o MapDisplay/cconfigpanelwidget.cpp

../obj/OBJ/chealthmonitorwidget.o: MapDisplay/chealthmonitorwidget.cpp MapDisplay/chealthmonitorwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/chealthmonitorwidget.o MapDisplay/chealthmonitorwidget.cpp

../obj/OBJ/chomepositionhighlightlayer.o: MapDisplay/chomepositionhighlightlayer.cpp MapDisplay/chomepositionhighlightlayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/chomepositionhighlightlayer.o MapDisplay/chomepositionhighlightlayer.cpp

../obj/OBJ/cinterfacespanelwidget.o: MapDisplay/cinterfacespanelwidget.cpp MapDisplay/cinterfacespanelwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cinterfacespanelwidget.o MapDisplay/cinterfacespanelwidget.cpp

../obj/OBJ/cpredictivemaintenancewidget.o: MapDisplay/cpredictivemaintenancewidget.cpp MapDisplay/cpredictivemaintenancewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cpredictivemaintenancewidget.o MapDisplay/cpredictivemaintenancewidget.cpp

../obj/OBJ/cppilayer.o: MapDisplay/cppilayer.cpp MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cppilayer.o MapDisplay/cppilayer.cpp

../obj/OBJ/crecordingwidget.o: MapDisplay/crecordingwidget.cpp MapDisplay/crecordingwidget.h \
		globalstructs.h \
		MapDisplay/creplaywindow.h \
		cdatawarehouse.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/crecordingwidget.o MapDisplay/crecordingwidget.cpp

../obj/OBJ/creplaywindow.o: MapDisplay/creplaywindow.cpp MapDisplay/creplaywindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/creplaywindow.o MapDisplay/creplaywindow.cpp

../obj/OBJ/csearchbeamlayer.o: MapDisplay/csearchbeamlayer.cpp MapDisplay/csearchbeamlayer.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/csearchbeamlayer.o MapDisplay/csearchbeamlayer.cpp

../obj/OBJ/csimulationwidget.o: MapDisplay/csimulationwidget.cpp MapDisplay/csimulationwidget.h \
		globalstructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/csimulationwidget.o MapDisplay/csimulationwidget.cpp

../obj/OBJ/ctracklayer.o: MapDisplay/ctracklayer.cpp MapDisplay/ctracklayer.h \
		cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/ctracklayer.o MapDisplay/ctracklayer.cpp

../obj/OBJ/ctracktablewidget.o: MapDisplay/ctracktablewidget.cpp MapDisplay/ctracktablewidget.h \
		cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/ctracktablewidget.o MapDisplay/ctracktablewidget.cpp

../obj/OBJ/customgradiantfillsymbollayer.o: MapDisplay/customgradiantfillsymbollayer.cpp MapDisplay/customgradiantfillsymbollayer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/customgradiantfillsymbollayer.o MapDisplay/customgradiantfillsymbollayer.cpp

../obj/OBJ/cdatawarehouse.o: cdatawarehouse.cpp cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cdatawarehouse.o cdatawarehouse.cpp

../obj/OBJ/cdrone.o: cdrone.cpp cdrone.h \
		globalstructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cdrone.o cdrone.cpp

../obj/OBJ/cudpreceiver.o: cudpreceiver.cpp cudpreceiver.h \
		globalstructs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cudpreceiver.o cudpreceiver.cpp

../obj/OBJ/main.o: main.cpp cmapmainwindow.h \
		MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		MapDisplay/cgismapcontroller.h \
		MapDisplay/cmapdisplay.h \
		globalmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/main.o main.cpp

../obj/OBJ/cmapmainwindow.o: cmapmainwindow.cpp cmapmainwindow.h \
		MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		../obj/UI/ui_cmapmainwindow.h \
		cppiwindow.h \
		MapDisplay/canalyticswidget.h \
		globalstructs.h \
		ccontrolswindow.h \
		cdatawarehouse.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cmapmainwindow.o cmapmainwindow.cpp

../obj/OBJ/cppiwindow.o: cppiwindow.cpp cppiwindow.h \
		MapDisplay/canalyticswidget.h \
		globalstructs.h \
		MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		MapDisplay/ctracktablewidget.h \
		cdatawarehouse.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cppiwindow.o cppiwindow.cpp

../obj/OBJ/ccontrolswindow.o: ccontrolswindow.cpp ccontrolswindow.h \
		MapDisplay/cconfigpanelwidget.h \
		MapDisplay/cchartswidget.h \
		MapDisplay/cinterfacespanelwidget.h \
		MapDisplay/canalyticswidget.h \
		globalstructs.h \
		MapDisplay/csimulationwidget.h \
		MapDisplay/crecordingwidget.h \
		MapDisplay/chealthmonitorwidget.h \
		MapDisplay/cpredictivemaintenancewidget.h \
		cdatawarehouse.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/ccontrolswindow.o ccontrolswindow.cpp

../obj/OBJ/cmapcanvas.o: MapDisplay/cmapcanvas.cpp MapDisplay/cmapcanvas.h \
		MapDisplay/cppilayer.h \
		MapDisplay/csearchbeamlayer.h \
		MapDisplay/ctracklayer.h \
		MapDisplay/customgradiantfillsymbollayer.h \
		globalmacros.h \
		cdatawarehouse.h \
		globalstructs.h \
		cudpreceiver.h \
		CoordinateConverter.h \
		matrix.h \
		cdrone.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/cmapcanvas.o MapDisplay/cmapcanvas.cpp

../obj/OBJ/matrix.o: matrix.cpp matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/matrix.o matrix.cpp

../obj/OBJ/qrc_myRes.o: ../obj/RCC/qrc_myRes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/qrc_myRes.o ../obj/RCC/qrc_myRes.cpp

../obj/OBJ/moc_canalyticswidget.o: ../obj/MOC/moc_canalyticswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_canalyticswidget.o ../obj/MOC/moc_canalyticswidget.cpp

../obj/OBJ/moc_cchartswidget.o: ../obj/MOC/moc_cchartswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cchartswidget.o ../obj/MOC/moc_cchartswidget.cpp

../obj/OBJ/moc_cconfigpanelwidget.o: ../obj/MOC/moc_cconfigpanelwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cconfigpanelwidget.o ../obj/MOC/moc_cconfigpanelwidget.cpp

../obj/OBJ/moc_chealthmonitorwidget.o: ../obj/MOC/moc_chealthmonitorwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_chealthmonitorwidget.o ../obj/MOC/moc_chealthmonitorwidget.cpp

../obj/OBJ/moc_chomepositionhighlightlayer.o: ../obj/MOC/moc_chomepositionhighlightlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_chomepositionhighlightlayer.o ../obj/MOC/moc_chomepositionhighlightlayer.cpp

../obj/OBJ/moc_cinterfacespanelwidget.o: ../obj/MOC/moc_cinterfacespanelwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cinterfacespanelwidget.o ../obj/MOC/moc_cinterfacespanelwidget.cpp

../obj/OBJ/moc_cpredictivemaintenancewidget.o: ../obj/MOC/moc_cpredictivemaintenancewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cpredictivemaintenancewidget.o ../obj/MOC/moc_cpredictivemaintenancewidget.cpp

../obj/OBJ/moc_cppilayer.o: ../obj/MOC/moc_cppilayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cppilayer.o ../obj/MOC/moc_cppilayer.cpp

../obj/OBJ/moc_crecordingwidget.o: ../obj/MOC/moc_crecordingwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_crecordingwidget.o ../obj/MOC/moc_crecordingwidget.cpp

../obj/OBJ/moc_creplaywindow.o: ../obj/MOC/moc_creplaywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_creplaywindow.o ../obj/MOC/moc_creplaywindow.cpp

../obj/OBJ/moc_csimulationwidget.o: ../obj/MOC/moc_csimulationwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_csimulationwidget.o ../obj/MOC/moc_csimulationwidget.cpp

../obj/OBJ/moc_ctracklayer.o: ../obj/MOC/moc_ctracklayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_ctracklayer.o ../obj/MOC/moc_ctracklayer.cpp

../obj/OBJ/moc_ctracktablewidget.o: ../obj/MOC/moc_ctracktablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_ctracktablewidget.o ../obj/MOC/moc_ctracktablewidget.cpp

../obj/OBJ/moc_cdatawarehouse.o: ../obj/MOC/moc_cdatawarehouse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cdatawarehouse.o ../obj/MOC/moc_cdatawarehouse.cpp

../obj/OBJ/moc_cdrone.o: ../obj/MOC/moc_cdrone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cdrone.o ../obj/MOC/moc_cdrone.cpp

../obj/OBJ/moc_cmapmainwindow.o: ../obj/MOC/moc_cmapmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cmapmainwindow.o ../obj/MOC/moc_cmapmainwindow.cpp

../obj/OBJ/moc_cppiwindow.o: ../obj/MOC/moc_cppiwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cppiwindow.o ../obj/MOC/moc_cppiwindow.cpp

../obj/OBJ/moc_ccontrolswindow.o: ../obj/MOC/moc_ccontrolswindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_ccontrolswindow.o ../obj/MOC/moc_ccontrolswindow.cpp

../obj/OBJ/moc_cmapcanvas.o: ../obj/MOC/moc_cmapcanvas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cmapcanvas.o ../obj/MOC/moc_cmapcanvas.cpp

../obj/OBJ/moc_cudpreceiver.o: ../obj/MOC/moc_cudpreceiver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ../obj/OBJ/moc_cudpreceiver.o ../obj/MOC/moc_cudpreceiver.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/../bin/RadarDisplay/bin || mkdir -p $(INSTALL_ROOT)/opt/../bin/RadarDisplay/bin
	$(QINSTALL_PROGRAM) ../bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/bin/RadarDisplay/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/bin/RadarDisplay/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/../bin/RadarDisplay/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

